/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ConsentBasic__factory } from "./ConsentBasic__factory";
export { ConsentMinimalEvent__factory } from "./ConsentMinimalEvent__factory";
export { ConsentOptimized__factory } from "./ConsentOptimized__factory";
